#include "gpk_enum.h"

#ifndef GPK_SYSEVENT_H_2094098237
#define GPK_SYSEVENT_H_2094098237

namespace gpk
{
	GDEFINE_ENUM_TYPE(SYSEVENT, uint16_t);
	GDEFINE_ENUM_VALUE(SYSEVENT, NOOP				,  0);
	GDEFINE_ENUM_VALUE(SYSEVENT, WINDOW_DESTROY		,  1);
	GDEFINE_ENUM_VALUE(SYSEVENT, WINDOW_CLOSE		,  2);
	GDEFINE_ENUM_VALUE(SYSEVENT, WINDOW_MOVE		,  3);
	GDEFINE_ENUM_VALUE(SYSEVENT, WINDOW_ACTIVATE	,  4);
	GDEFINE_ENUM_VALUE(SYSEVENT, WINDOW_DEACTIVATE	,  5);
	GDEFINE_ENUM_VALUE(SYSEVENT, WINDOW_RESIZE		,  6);
	GDEFINE_ENUM_VALUE(SYSEVENT, WINDOW_REDRAW		,  7);
	GDEFINE_ENUM_VALUE(SYSEVENT, WINDOW_SHOW		,  8);
	GDEFINE_ENUM_VALUE(SYSEVENT, WINDOW_HIDE		,  9);
	GDEFINE_ENUM_VALUE(SYSEVENT, WINDOW_CREATE		, 10);
	GDEFINE_ENUM_VALUE(SYSEVENT, KEY_UP				, 11);
	GDEFINE_ENUM_VALUE(SYSEVENT, KEY_DOWN			, 12);
	GDEFINE_ENUM_VALUE(SYSEVENT, SYSKEY_DOWN		, 13);		
	GDEFINE_ENUM_VALUE(SYSEVENT, SYSKEY_UP			, 14);		
	GDEFINE_ENUM_VALUE(SYSEVENT, MOUSE_UP			, 15);
	GDEFINE_ENUM_VALUE(SYSEVENT, MOUSE_DOWN			, 16);
	GDEFINE_ENUM_VALUE(SYSEVENT, MOUSE_DBLCLK		, 17);	
	GDEFINE_ENUM_VALUE(SYSEVENT, MOUSE_WHEEL		, 18);	
	GDEFINE_ENUM_VALUE(SYSEVENT, MOUSE_POSITION		, 19);	
	GDEFINE_ENUM_VALUE(SYSEVENT, TOUCH_BEGIN		, 20);	
	GDEFINE_ENUM_VALUE(SYSEVENT, TOUCH_END			, 21);
	GDEFINE_ENUM_VALUE(SYSEVENT, TOUCH_UPDATE		, 22);	
	GDEFINE_ENUM_VALUE(SYSEVENT, TOUCH_OWNERSHIP	, 23);		
	GDEFINE_ENUM_VALUE(SYSEVENT, CHAR				, 24);
	GDEFINE_ENUM_VALUE(SYSEVENT, MINMAXINFO			, 25);
	GDEFINE_ENUM_VALUE(SYSEVENT, JOY_BUTTON_DOWN	, 26);
	GDEFINE_ENUM_VALUE(SYSEVENT, JOY_BUTTON_UP		, 27);
	GDEFINE_ENUM_VALUE(SYSEVENT, JOY_MOVE			, 28);

	struct SSysEvent {
		::gpk::SYSEVENT				Type;
		::gpk::array_pod<uint8_t>	Data;
	};

} // namespace 

#endif // GPK_SYSEVENT_H_2094098237
