#include "llc_enum.h"

#ifndef LLC_AXIS_H_23627
#define LLC_AXIS_H_23627

namespace llc
{
#pragma pack(push, 1)
	GDEFINE_ENUM_TYPE(AXIS, uint8_t);
	GDEFINE_ENUM_VALUE(AXIS, ORIGIN		, 0x0);
	GDEFINE_ENUM_VALUE(AXIS, X_NEGATIVE	, 0x1);
	GDEFINE_ENUM_VALUE(AXIS, X_POSITIVE	, 0x2);
	GDEFINE_ENUM_VALUE(AXIS, Y_NEGATIVE	, 0x4);
	GDEFINE_ENUM_VALUE(AXIS, Y_POSITIVE	, 0x8);
	GDEFINE_ENUM_VALUE(AXIS, Z_NEGATIVE	, 0x10);
	GDEFINE_ENUM_VALUE(AXIS, Z_POSITIVE	, 0x20);
	
	GDEFINE_ENUM_TYPE(DIRECTION, uint8_t);
	GDEFINE_ENUM_VALUE(DIRECTION, ORIGIN, AXIS_ORIGIN);
	GDEFINE_ENUM_VALUE(DIRECTION, BACK	, AXIS_X_NEGATIVE);
	GDEFINE_ENUM_VALUE(DIRECTION, FRONT	, AXIS_X_POSITIVE);
	GDEFINE_ENUM_VALUE(DIRECTION, DOWN	, AXIS_Y_NEGATIVE);
	GDEFINE_ENUM_VALUE(DIRECTION, UP	, AXIS_Y_POSITIVE);
	GDEFINE_ENUM_VALUE(DIRECTION, LEFT	, AXIS_Z_NEGATIVE);
	GDEFINE_ENUM_VALUE(DIRECTION, RIGHT	, AXIS_Z_POSITIVE);

	GDEFINE_ENUM_TYPE(ALIGN, uint8_t);
	GDEFINE_ENUM_VALUE(ALIGN, ORIGIN		, 0);
	GDEFINE_ENUM_VALUE(ALIGN, RIGHT			, ((uint8_t)AXIS_X_POSITIVE));
	GDEFINE_ENUM_VALUE(ALIGN, LEFT			, ((uint8_t)AXIS_X_NEGATIVE));
	GDEFINE_ENUM_VALUE(ALIGN, BOTTOM		, ((uint8_t)AXIS_Y_POSITIVE));
	GDEFINE_ENUM_VALUE(ALIGN, TOP			, ((uint8_t)AXIS_Y_NEGATIVE));
	GDEFINE_ENUM_VALUE(ALIGN, FAR			, ((uint8_t)AXIS_Z_POSITIVE));
	GDEFINE_ENUM_VALUE(ALIGN, NEAR			, ((uint8_t)AXIS_Z_NEGATIVE));
	GDEFINE_ENUM_VALUE(ALIGN, HCENTER		, ALIGN_LEFT	| ALIGN_RIGHT);
	GDEFINE_ENUM_VALUE(ALIGN, VCENTER		, ALIGN_TOP		| ALIGN_BOTTOM);
	GDEFINE_ENUM_VALUE(ALIGN, DCENTER		, ALIGN_FAR		| ALIGN_NEAR);
	GDEFINE_ENUM_VALUE(ALIGN, TOP_LEFT		, ALIGN_TOP		| ALIGN_LEFT);
	GDEFINE_ENUM_VALUE(ALIGN, TOP_RIGHT		, ALIGN_TOP		| ALIGN_RIGHT);
	GDEFINE_ENUM_VALUE(ALIGN, BOTTOM_LEFT	, ALIGN_BOTTOM	| ALIGN_LEFT);
	GDEFINE_ENUM_VALUE(ALIGN, BOTTOM_RIGHT	, ALIGN_BOTTOM	| ALIGN_RIGHT);
	GDEFINE_ENUM_VALUE(ALIGN, CENTER_TOP	, ALIGN_HCENTER	| ALIGN_TOP);
	GDEFINE_ENUM_VALUE(ALIGN, CENTER_BOTTOM	, ALIGN_HCENTER	| ALIGN_BOTTOM);
	GDEFINE_ENUM_VALUE(ALIGN, CENTER_LEFT	, ALIGN_VCENTER	| ALIGN_LEFT);
	GDEFINE_ENUM_VALUE(ALIGN, CENTER_RIGHT	, ALIGN_VCENTER	| ALIGN_RIGHT);
	GDEFINE_ENUM_VALUE(ALIGN, CENTER		, ALIGN_VCENTER	| ALIGN_HCENTER);
	GDEFINE_ENUM_VALUE(ALIGN, XCENTER		, ALIGN_LEFT	| ALIGN_RIGHT);
	GDEFINE_ENUM_VALUE(ALIGN, YCENTER		, ALIGN_TOP		| ALIGN_BOTTOM);
	GDEFINE_ENUM_VALUE(ALIGN, ZCENTER		, ALIGN_FAR		| ALIGN_NEAR);
	#pragma pack(pop)
} // namespace

#endif // LLC_AXIS_H_23627